import json
import time
from pathlib import Path
from app.models.script_schema import BatchPromptResponse

class ImagePromptService:
    def __init__(self, llm_client, prompt_dir: Path, output_dir: Path = None):
        self.llm = llm_client
        self.base_dir = Path(__file__).resolve().parent.parent.parent
        self.prompt_dir = prompt_dir
        
        self.output_dir = output_dir or (self.base_dir / "assets" / "outputs")
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _read_prompt_instructions(self) -> str:
        with open(self.prompt_dir / "image_prompts_instructions.txt", 'r', encoding='utf-8') as f:
            return f.read()

    def generate_all_prompts(self, transcription_json_path: Path, raw_title: str, script_text: str):
        print("\n--- GENERATING HIERARCHICAL IMAGE PROMPTS ---")
        
        # Load the smart batches generated by WhisperX
        with open(transcription_json_path, 'r', encoding='utf-8') as f:
            transcription_data = json.load(f)
            
        instructions = self._read_prompt_instructions()
        all_compiled_shots = []

        batches = transcription_data.get("batches", [])
        total_batches = len(batches)

        for idx, batch in enumerate(batches):
            print(f"\nProcessing Audio Batch {batch['batch_id']} of {total_batches} ({batch['duration']}s)...")
            
            # Serialize the specific segment timestamps for this batch window
            batch_segments_context = json.dumps(batch["segments"], indent=2)
            
            # Construct the comprehensive, self-contained context window
            user_prompt = (
                f"Video Raw Title: {raw_title}\n\n"
                f"Full Narration Script:\n{script_text}\n\n"
                f"--- CURRENT BATCH SEGMENTS TO PROCESS ---\n"
                f"{batch_segments_context}\n\n"
                f"--- INSTRUCTIONS ---\n"
                f"{instructions}"
            )

            # Fire structured generation
            print(f"Sending Batch {batch['batch_id']} to Gemini API...")
            raw_response = self.llm.generate_json(user_prompt, response_model=BatchPromptResponse)
            
            try:
                validated_batch = BatchPromptResponse(**json.loads(raw_response))
                all_compiled_shots.extend(validated_batch.shots)
                print(f"Successfully processed {len(validated_batch.shots)} shots for Batch {batch['batch_id']}.")
            except Exception as e:
                print(f"[ERROR] Failed parsing responses for Batch {batch['batch_id']}: {e}")

            # Rate-limiting cooldown to safeguard the Gemini free tier limits
            if idx < total_batches - 1:
                print("Waiting 4 seconds to protect API rate limits...")
                time.sleep(4)

        # Sort all compiled elements chronologically to ensure absolute sequencing stability
        all_compiled_shots.sort(key=lambda x: x.start_time)

        # Write the MoviePy-friendly flat txt format
        txt_output_path = self.output_dir / "time_stamped_prompts.txt"
        with open(txt_output_path, 'w', encoding='utf-8') as txt_file:
            for shot in all_compiled_shots:
                txt_file.write(f"[{shot.start_time}] {shot.image_prompt}\n")

        print(f"\n[Success] Finalized production-ready layout saved to: {txt_output_path}")
        return txt_output_path